In [4]:
import numpy as np
import random
from numpy import linalg as la


#part1a
print("Link matrix L:")
m = np.array([[0,0,1/3,0,0],[1/3,0,1/3,1/2,0],[0,0,0,1/2,1],[1/3,0,1/3,0,0],[1/3,1,0,0,0]])
print(m)
print('')

Link matrix L:
[[0.         0.         0.33333333 0.         0.        ]
 [0.33333333 0.         0.33333333 0.5        0.        ]
 [0.         0.         0.         0.5        1.        ]
 [0.33333333 0.         0.33333333 0.         0.        ]
 [0.33333333 1.         0.         0.         0.        ]]



In [5]:
#part1b
eigvals, eigvecs = la.eig(m)
order_eigval = np.absolute(eigvals).argsort()[::-1]
eigvals = eigvals[order_eigval]
eigvecs = eigvecs[:, order_eigval]
r = eigvecs[:,0] # r = principle eigenvector

print('Percentage numbers of surfers: ')
print(100*np.real(r/np.sum(r)))
print('')

Percentage numbers of surfers: 
[10.34482759 20.68965517 31.03448276 13.79310345 24.13793103]



In [7]:
#part 2a
r = np.array([1/5,1/5,1/5,1/5,1/5])
print('Initial vector r: ')
print(r)

print('')

Initial vector r: 
[0.2 0.2 0.2 0.2 0.2]



In [8]:
#part 2b
def multiply_matrices(p,q):
    return np.matmul(p,q)

def percentage(M,R):  #used in 3b, 4b
    norm = 0
    pre_norm = 9999
    iteration = 0
    while ((abs(pre_norm-norm) > 0.005)):
        R = multiply_matrices(M, R)
        if (iteration == 0):
            norm = la.norm(R)
        else:
            pre_norm = norm
            norm = la.norm(R)

        iteration += 1

    print("Number of iterations:", iteration)
    R = (R*100)

    return R

print(percentage(m,r))
print('')

Number of iterations: 2
[10.         18.88888889 33.33333333 12.22222222 25.55555556]



In [9]:
#Part 3a
n= 6
J = np.ones((n,n))
d = 0.5
L = np.array([[0,0,1/3,0,0,0],[1/3,0,1/3,1/2,0,0],[0,0,0,1/2,1,0],[1/3,0,1/3,0,0,0],[1/3,1,0,0,0,0],[0,0,0,0,0,1]])
M = (d*L)+(((1-d)/n)*J)
print('Matrix M:')
print(M)
print('')

Matrix M:
[[0.08333333 0.08333333 0.25       0.08333333 0.08333333 0.08333333]
 [0.25       0.08333333 0.25       0.33333333 0.08333333 0.08333333]
 [0.08333333 0.08333333 0.08333333 0.33333333 0.58333333 0.08333333]
 [0.25       0.08333333 0.25       0.08333333 0.08333333 0.08333333]
 [0.25       0.58333333 0.08333333 0.08333333 0.08333333 0.08333333]
 [0.08333333 0.08333333 0.08333333 0.08333333 0.08333333 0.58333333]]



In [10]:
#part 3b
r_2 = np.array([1/6,1/6,1/6,1/6,1/6,1/6])
print(percentage(M,r_2))
print('')

Number of iterations: 2
[11.80555556 17.12962963 21.52777778 13.65740741 19.21296296 16.66666667]



In [11]:
#Part 4a
def generate_network(N):
  o = np.zeros((N, N), dtype=float)

  for x in range(0,N):
      for y in range(0,N):
        o[x][y] = random.randint(0,1)

  trans = np.transpose(o)

  for x in range(0,N):
      amount=0
      for y in range(0,N):
          if (trans[x][y] == 1):
              amount+=1
      for t in range(0, N):
          if (trans[x][t] == 1):
              trans[x][t] /= amount
  trans = np.transpose(trans)
  print(trans)

  return trans

n = int(input("Enter value n for n*n matrix\n"))
ranlink = generate_network(n)

Enter value n for n*n matrix
5
[[0.33333333 0.25       0.33333333 0.         0.25      ]
 [0.         0.         0.33333333 0.33333333 0.        ]
 [0.         0.25       0.         0.33333333 0.25      ]
 [0.33333333 0.25       0.         0.33333333 0.25      ]
 [0.33333333 0.25       0.33333333 0.         0.25      ]]


In [12]:
#Part 4b
d = float(input("Enter damping factor d\n"))

def page_rank(X,d,n):

   J_2 = np.ones((n,n))
   M_2 = (d*X)+(((1-d)/n)*J_2)
   print(M_2)
   r3 = []
   for i in range(n):
       r3.append(1/n)

   p = percentage(M_2, r3)

   return p


print(page_rank(ranlink,d,n))

Enter damping factor d
0.5
[[0.26666667 0.225      0.26666667 0.1        0.225     ]
 [0.1        0.1        0.26666667 0.26666667 0.1       ]
 [0.1        0.225      0.1        0.26666667 0.225     ]
 [0.26666667 0.225      0.1        0.26666667 0.225     ]
 [0.26666667 0.225      0.26666667 0.1        0.225     ]]
Number of iterations: 2
[21.45833333 16.66666667 18.40277778 22.01388889 21.45833333]
