In [2]:
import numpy as np
from numpy import asarray
from PIL import Image

#Part 1a.
myFILE = "image1.jpg"
img = Image.open(myFILE)

gsFull = np.array((img).convert('L')) / 255
print("gsFull with values between 0 and 1: ")
print(gsFull)

gsFull with values between 0 and 1: 
[[0.61960784 0.59607843 0.54509804 ... 0.68235294 0.69411765 0.68627451]
 [0.58431373 0.56470588 0.52941176 ... 0.74117647 0.75294118 0.74117647]
 [0.61176471 0.59215686 0.56470588 ... 0.7254902  0.73333333 0.7254902 ]
 ...
 [0.62745098 0.65098039 0.66666667 ... 0.30980392 0.30588235 0.3372549 ]
 [0.67843137 0.68627451 0.68235294 ... 0.25098039 0.22745098 0.20392157]
 [0.65882353 0.68235294 0.69803922 ... 0.30196078 0.27843137 0.22745098]]


In [3]:
#Part 1b.
U, s, V = np.linalg.svd(gsFull)

gr_im = asarray(gsFull)
print("Shape of U:",U.shape)
print("Shape of s:",s.shape)
print("Shape of V:",V.shape)

b = np.diag(s.ravel()) #create a matrix with s in the diagonals

width, height = img.size
c = np.zeros((height-width, 908)) #Used to add rows of zeros to s for

result = np.vstack((b,c))
print("New shape for s:",result.shape)

Shape of U: (1024, 1024)
Shape of s: (908,)
Shape of V: (908, 908)
New shape for s: (1024, 908)


In [4]:
#Part 1c
Reconstructed = U @ result @ V
print("Is the image reconstructed correctly?")
print(np.allclose(gsFull,Reconstructed))

Image.fromarray(Reconstructed * 255).show()

Is the image reconstructed correctly?
True


In [5]:
#Part 2a

Rank = 20
print("Shapes of the approx matrices: ")
u = np.array(U[:, :Rank]) #Take the height of the original matrix and a width of Rank
print(u.shape)

S = result[:Rank,:Rank]  #Take the height and width of the diagonal Rank
print(S.shape)

v = np.array(V[:Rank,:]) #Take the width of rank and height of original
print(v.shape)

Approx = u @ S @ v
Image.fromarray(Approx * 255).show()


Shapes of the approx matrices: 
(1024, 20)
(20, 20)
(20, 908)


In [6]:
#Part 2b

diff = gsFull - Approx
diff = np.linalg.norm(diff)
print("Difference:",diff)


Difference: 50.98851882547021


In [7]:
#Part 2c

Elements_inU = height * Rank
Elements_inS = Rank * Rank
Elements_inV = width * Rank

Perc = ((Elements_inU + Elements_inS + Elements_inV) / (height * width)) * 100
print("Elements required:", Perc, '%')


Elements required: 4.198788546255507 %


In [8]:
#Part 2d

Total_O = height * width
Total_A = 0
R = 0

while Total_O > Total_A:
 Elements_inU = height * R
 Elements_inS = R
 Elements_inV = width * R
 Total_A = Elements_inU + Elements_inS + Elements_inV
 R+=1

print(Total_A)
print(Total_O)
print("At rank:", R)


931706
929792
At rank: 483


In [9]:
#Part 3

Rnk = input("Input the rank: ")
Rnk = int(Rnk)
myFile_2 = input("Input file name (ex: image1.jpg): ")

Imge = Image.open(myFile_2)
gsFull_2 = np.array((Imge).convert('L')) / 255

def approx_im(RANK, GSFULL):
  width, height = gsFull_2.shape
  U_2, s_2, V_2 = np.linalg.svd(GSFULL)
  if(width > height):
      b = np.diag(s_2.ravel())
      c = np.zeros((width-height, height))
      result = np.vstack((b, c))
      result = result.transpose()

  else:
   b = np.diag(s_2.ravel())  # create a matrix with s in the diagonals
   c = np.zeros((height - width, width))
   result = np.vstack((b, c))

  u = np.array(U_2[:, :RANK])  # Take the height of the original matrix and a width of Rank
  S = result[:RANK, :RANK]  # Take the height and width of the diagonal Rank
  v = np.array(V_2[:RANK, :])  # Take the width of rank and height of original

  Approx = u @ S @ v

  diff_2 = GSFULL - Approx
  diff_2 = np.linalg.norm(diff_2)

  Elements_inU = height * RANK
  Elements_inS = RANK * RANK
  Elements_inV = width * RANK

  Perc = ((Elements_inU + Elements_inS + Elements_inV) / (height * width)) * 100

  return(Approx,diff_2,Perc)


A, D, P = approx_im(Rnk,gsFull_2)
print("Difference:",D)
print("Elements required:",P, '%')
Image.fromarray(A * 255).show()

Input the rank: 20
Input file name (ex: image1.jpg): attack.jpg
Difference: 124.99972001074124
Elements required: 3.5000000000000004 %
